export const constantVariables = {
  createAcc: 'Create your account',
  emailLabel: 'Email',
  passwordLabel: 'Password',
  signUpButton: 'Sign Up',
  loginLink: 'Already have an account? ',
  loginLinkHighlight: 'Login',
  emailError: 'Please enter a valid email address',
  passwordError:'Password must be at least 8 characters with one uppercase and one special character',
  modalButton: 'OK',
  modalTextDefault: '',
  subtitle: 'Sign in to your account',
  loginButton: 'Login',
  signUpLink: 'Don’t have an account? ',
  signUpLinkHighlight: 'Sign Up',
  modalText: 'Invalid Credentials',
  LOGOUT_TEXT: 'Logout',
  API_URL: 'https://randomuser.me/api/?results=1000',
  MODAL_TEXT: 'Are you sure you want to log out?',
  CANCEL_TEXT: 'Cancel',
  CONFIRM_TEXT: 'Logout',
};
